### ISSUE TITLE
App Priorities

### ISSUE THREAD

**Issue by mckelveygreg** [Hack4Eugene/spark-sert2521-2019#1]
This is a fluid issue tracking priorities:
- [ ] Looks like https://www.carryitforward.net/
- [ ] Super Mobile first/friendly
- [ ] Snappy, quick (backend issue?) @JacksonCoder 

(Feel free to add/edit as you see fit!)

**Comment by snowsignal** [comment]
Is this just for frontend priorities?

**Comment by snowsignal** [comment]
@mckelveygreg I recommend we merge this with another issue checklist.

**Comment by mckelveygreg** [comment]
@jacksoncoder go for it!
