### ISSUE TITLE
Create Person Card

### ISSUE THREAD

**Issue by gnawinganimal** [Hack4Eugene/spark-sert2521-2019#13]
Person Cards should include
- [ ] Photo
- [ ] Bio
- [ ] Items
  - [ ] Name
  - [ ] Progress Bar
  - [ ] Price 
-[ ] (If user is an admin) Show a plus button to take the admin to a page where they can edit person information and new requested items. Edit Person page would be same as create Person Page but repopulated with values from DB

**Comment by will-hou** [comment]
I can start the home screen person card
