### ISSUE TITLE
Create Add Person Page

### ISSUE THREAD

**Issue by will-hou** [Hack4Eugene/spark-sert2521-2019#19]
This page will only be accessible by admin users. Page for an admin to upload a profile picture, enter person name, and write a bio. Also gives ability for user to add requested items for the person

**Comment by mckelveygreg** [comment]
I'm thinking of making this with [formik](https://github.com/jaredpalmer/formik). It helps manage a lot of the form madness.

@andrewda Do we have the Person Schema set? and what endpoint do I hit? (or could you point me to the read me? :) )

**Comment by mckelveygreg** [comment]
So far, the page has a form, and formats the information correctly.
TODO:
- [x] split post into new person, and then post items to slug
- [x] redirect or success message?
